[package]
name = "score"
version = "0.0.0"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "e13e78d" }

[addresses]
std =  "0x1"
minitia_std = "0x1"